<a href="https://colab.research.google.com/github/saragadamhemanth17/e40-mlops/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Preprocessing Steps

First, let's load the `Titanic-Dataset.csv` file into a pandas DataFrame and display the first few rows to understand its structure.

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Titanic-Dataset.csv')

# Display the first 5 rows and basic information
print("Dataset Head:")
display(df.head())

print("\nDataset Info:")
df.info()

print("\nMissing values before handling:")
display(df.isnull().sum())

Dataset Head:


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S



Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Missing values before handling:


,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


### Handle Missing Values

From the `df.info()` and `df.isnull().sum()` outputs, we can see that 'Age', 'Cabin', and 'Embarked' columns have missing values.

*   **Age**: We'll fill missing 'Age' values with the median age.
*   **Cabin**: This column has a large number of missing values and might not be directly useful. We'll drop it.
*   **Embarked**: This column has only a few missing values. We'll fill them with the most frequent value (mode).

In [2]:
# Fill missing 'Age' values with the median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Drop the 'Cabin' column due to many missing values
df.drop('Cabin', axis=1, inplace=True)

# Fill missing 'Embarked' values with the mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

print("Missing values after handling:")
display(df.isnull().sum())

Missing values after handling:


/tmp/ipykernel_4906/2072400945.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipykernel_4906/2072400945.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', tr

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,0
SibSp,0
Parch,0
Ticket,0
Fare,0


### Encode Categorical Variables

We need to convert categorical features ('Sex' and 'Embarked') into numerical representations. We'll use one-hot encoding for 'Embarked' and map 'Sex' to numerical values.

In [3]:
# Encode 'Sex' column: Male=0, Female=1
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# One-hot encode 'Embarked' column
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Drop 'Name' and 'Ticket' columns as they are not useful for modeling
df.drop(['Name', 'Ticket', 'PassengerId'], axis=1, inplace=True)

print("\nDataFrame after encoding categorical variables and dropping irrelevant columns:")
display(df.head())
df.info()


DataFrame after encoding categorical variables and dropping irrelevant columns:


,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,3,0,22.0,1,0,7.2500,False,True
1,1,1,1,38.0,1,0,71.2833,False,False
2,1,3,1,26.0,0,0,7.9250,False,True
3,1,1,1,35.0,1,0,53.1000,False,True
4,0,3,0,35.0,0,0,8.0500,False,True


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Survived    891 non-null    int64  
 1   Pclass      891 non-null    int64  
 2   Sex         891 non-null    int64  
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64  
 5   Parch       891 non-null    int64  
 6   Fare        891 non-null    float64
 7   Embarked_Q  891 non-null    bool   
 8   Embarked_S  891 non-null    bool   
dtypes: bool(2), float64(2), int64(5)
memory usage: 50.6 KB


### Normalize Data

Numerical features (`Age`, `Fare`, `SibSp`, `Parch`) often benefit from scaling. We'll use StandardScaler to normalize these features, which transforms them to have a mean of 0 and a standard deviation of 1.

In [4]:
from sklearn.preprocessing import StandardScaler

# Define numerical columns to normalize (excluding 'Survived' which is the target)
numerical_cols = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the numerical columns
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("\nDataFrame after normalizing numerical features:")
display(df.head())


DataFrame after normalizing numerical features:


,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,0.827377,0,-0.565736,0.432793,-0.473674,-0.502445,False,True
1,1,-1.566107,1,0.663861,0.432793,-0.473674,0.786845,False,False
2,1,0.827377,1,-0.258337,-0.474545,-0.473674,-0.488854,False,True
3,1,-1.566107,1,0.433312,0.432793,-0.473674,0.420730,False,True
4,0,0.827377,0,0.433312,-0.474545,-0.473674,-0.486337,False,True


### Split Data into Training and Testing Sets

Finally, we'll split the preprocessed data into features (X) and the target variable (y), and then divide these into training and testing sets to prepare for model building.

In [5]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('Survived', axis=1)
y = df['Survived']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"\nX_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

print("\nPreprocessing steps completed! The data is now ready for model training.")


X_train shape: (712, 8)
y_train shape: (712,)
X_test shape: (179, 8)
y_test shape: (179,)

Preprocessing steps completed! The data is now ready for model training.


## Model Training and Evaluation

Now, let's train a Logistic Regression model using the `X_train` and `y_train` datasets and then evaluate its performance on the `X_test` and `y_test` datasets.

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Initialize and train the Logistic Regression model
model = LogisticRegression(random_state=42, solver='liblinear') # 'liblinear' solver is good for small datasets and binary classification
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!


### Model Evaluation

Let's evaluate the trained model using various metrics such as accuracy, precision, recall, F1-score, and display the confusion matrix.

In [7]:
# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"\nModel Evaluation Report:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")

print("\nConfusion Matrix:")
display(pd.DataFrame(conf_matrix,
                     index=['Actual Not Survived', 'Actual Survived'],
                     columns=['Predicted Not Survived', 'Predicted Survived']))


Model Evaluation Report:
Accuracy:  0.8045
Precision: 0.7931
Recall:    0.6667
F1-Score:  0.7244

Confusion Matrix:


,Predicted Not Survived,Predicted Survived
Actual Not Survived,98,12
Actual Survived,23,46


### Summary of Training and Testing

The Logistic Regression model has been trained and evaluated. Here's a brief summary of its performance:

*   **Accuracy**: **0.8045** - The proportion of correctly classified instances.
*   **Precision**: **0.7931** - The proportion of positive identifications that were actually correct.
*   **Recall**: **0.6667** - The proportion of actual positives that were identified correctly.
*   **F1-Score**: **0.7244** - The harmonic mean of precision and recall, providing a single metric that balances both.
*   **Confusion Matrix**: It shows the counts of true positives, true negatives, false positives, and false negatives:

| | Predicted Not Survived | Predicted Survived |
| :---------------------- | :--------------------- | :----------------- |
| **Actual Not Survived** | 98 | 12 |
| **Actual Survived** | 23 | 46 |

## Automating Preprocessing with a Pipeline

Let's create a preprocessing pipeline to automate the steps and ensure consistency. This pipeline will handle missing values, scale numerical features, and encode categorical features. We'll then integrate this into a full modeling pipeline.

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Reload the original dataset to demonstrate the full pipeline from raw data
df_raw = pd.read_csv('/content/Titanic-Dataset.csv')

# Define features (X) and target (y)
X_raw = df_raw.drop('Survived', axis=1)
y_raw = df_raw['Survived']

# Drop columns that are not useful for modeling or have too many missing values
X_raw = X_raw.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

# Split data into training and testing sets *before* preprocessing
X_train_initial, X_test_initial, y_train, y_test = train_test_split(X_raw, y_raw, test_size=0.2, random_state=42, stratify=y_raw)

print("Initial data split for pipeline:")
print(f"X_train_initial shape: {X_train_initial.shape}")
print(f"X_test_initial shape: {X_test_initial.shape}")

Initial data split for pipeline:
X_train_initial shape: (712, 7)
X_test_initial shape: (179, 7)


### Define Preprocessing Steps within the Pipeline

We'll use `ColumnTransformer` to apply different transformations to numerical and categorical columns. For numerical features, we'll impute missing values with the median and then scale them. For categorical features, we'll impute missing values with the most frequent value and then apply one-hot encoding.

In [9]:
# Identify numerical and categorical columns
numerical_features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
categorical_features = ['Sex', 'Embarked']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a preprocessor using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

print("Preprocessing ColumnTransformer defined.")

Preprocessing ColumnTransformer defined.


### Build and Train the Full Machine Learning Pipeline

Now, we combine the `preprocessor` with a `LogisticRegression` model into a single `Pipeline` and train it on our initial training data.

In [10]:
# Create the full pipeline including preprocessing and the model
full_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42, solver='liblinear'))
])

# Train the pipeline
full_pipeline.fit(X_train_initial, y_train)

print("Full pipeline (preprocessing + Logistic Regression) trained successfully!")

Full pipeline (preprocessing + Logistic Regression) trained successfully!


### Evaluate the Pipeline Model

Let's evaluate the performance of the model trained using the pipeline on the test set.

In [11]:
# Make predictions on the initial test set using the full pipeline
y_pred_pipeline = full_pipeline.predict(X_test_initial)

# Calculate evaluation metrics for the pipeline model
accuracy_pipeline = accuracy_score(y_test, y_pred_pipeline)
precision_pipeline = precision_score(y_test, y_pred_pipeline)
recall_pipeline = recall_score(y_test, y_pred_pipeline)
f1_pipeline = f1_score(y_test, y_pred_pipeline)
conf_matrix_pipeline = confusion_matrix(y_test, y_pred_pipeline)

print(f"\nPipeline Model Evaluation Report:")
print(f"Accuracy:  {accuracy_pipeline:.4f}")
print(f"Precision: {precision_pipeline:.4f}")
print(f"Recall:    {recall_pipeline:.4f}")
print(f"F1-Score:  {f1_pipeline:.4f}")

print("\nConfusion Matrix (Pipeline Model):")
display(pd.DataFrame(conf_matrix_pipeline,
                     index=['Actual Not Survived', 'Actual Survived'],
                     columns=['Predicted Not Survived', 'Predicted Survived']))


Pipeline Model Evaluation Report:
Accuracy:  0.8045
Precision: 0.7931
Recall:    0.6667
F1-Score:  0.7244

Confusion Matrix (Pipeline Model):


,Predicted Not Survived,Predicted Survived
Actual Not Survived,98,12
Actual Survived,23,46


## Saving Processed Data for Reuse

We can extract the preprocessed training and testing data from our pipeline's `preprocessor` step and save them to CSV files for future use. This is useful if you want to use the preprocessed data with other models or for further analysis without retraining the preprocessing steps.

In [12]:
# Transform the initial training and test data using the fitted preprocessor
X_train_processed_array = preprocessor.fit_transform(X_train_initial, y_train) # Fit and transform on train
X_test_processed_array = preprocessor.transform(X_test_initial) # Only transform on test

# Get feature names for the preprocessed data
onehot_features = full_pipeline.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_features)
all_processed_features = numerical_features + list(onehot_features)

# Convert to DataFrame
X_train_processed = pd.DataFrame(X_train_processed_array, columns=all_processed_features)
X_test_processed = pd.DataFrame(X_test_processed_array, columns=all_processed_features)

# Save the processed data and target variables to CSV files
X_train_processed.to_csv('X_train_processed.csv', index=False)
X_test_processed.to_csv('X_test_processed.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)

print("Preprocessed data saved to: 'X_train_processed.csv', 'X_test_processed.csv', 'y_train.csv', 'y_test.csv'")

print("\nHead of X_train_processed:")
display(X_train_processed.head())

Preprocessed data saved to: 'X_train_processed.csv', 'X_test_processed.csv', 'y_train.csv', 'y_test.csv'

Head of X_train_processed:


,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0.829568,-0.081135,-0.465084,-0.466183,0.513812,0.0,1.0,0.0,0.0,1.0
1,-0.370945,-0.081135,-0.465084,-0.466183,-0.662563,0.0,1.0,0.0,0.0,1.0
2,-1.571457,-0.081135,-0.465084,-0.466183,3.955399,0.0,1.0,0.0,0.0,1.0
3,0.829568,-0.887827,-0.465084,0.727782,-0.467874,1.0,0.0,0.0,0.0,1.0
4,-0.370945,0.110934,0.478335,0.727782,-0.115977,1.0,0.0,0.0,0.0,1.0


## Comparison of Results: Manual vs. Pipeline Preprocessing

Let's compare the evaluation metrics from the manual preprocessing approach (which we executed earlier) with the automated pipeline approach.

In [13]:
# Previous manual preprocessing results (captured from earlier output)
accuracy_manual = 0.8045
precision_manual = 0.7931
recall_manual = 0.6667
f1_manual = 0.7244

print("\n--- Comparison of Model Performance ---")
print("\nManual Preprocessing Results:")
print(f"Accuracy:  {accuracy_manual:.4f}")
print(f"Precision: {precision_manual:.4f}")
print(f"Recall:    {recall_manual:.4f}")
print(f"F1-Score:  {f1_manual:.4f}")

print("\nPipeline Preprocessing Results:")
print(f"Accuracy:  {accuracy_pipeline:.4f}")
print(f"Precision: {precision_pipeline:.4f}")
print(f"Recall:    {recall_pipeline:.4f}")
print(f"F1-Score:  {f1_pipeline:.4f}")

print("\n--- Observations ---")
print("The performance metrics are very similar between the manual and pipeline approaches. This indicates that the pipeline successfully replicated the preprocessing steps.")
print("Using a pipeline offers several advantages:")
print("1. **Automation**: All steps are encapsulated and run in order automatically.")
print("2. **Consistency**: Prevents data leakage and ensures the same transformations are applied to training and test data.")
print("3. **Reproducibility**: Easier to reproduce results and share workflows.")
print("4. **Streamlined Workflow**: Simplifies hyperparameter tuning and cross-validation.")


--- Comparison of Model Performance ---

Manual Preprocessing Results:
Accuracy:  0.8045
Precision: 0.7931
Recall:    0.6667
F1-Score:  0.7244

Pipeline Preprocessing Results:
Accuracy:  0.8045
Precision: 0.7931
Recall:    0.6667
F1-Score:  0.7244

--- Observations ---
The performance metrics are very similar between the manual and pipeline approaches. This indicates that the pipeline successfully replicated the preprocessing steps.
Using a pipeline offers several advantages:
1. **Automation**: All steps are encapsulated and run in order automatically.
2. **Consistency**: Prevents data leakage and ensures the same transformations are applied to training and test data.
3. **Reproducibility**: Easier to reproduce results and share workflows.
4. **Streamlined Workflow**: Simplifies hyperparameter tuning and cross-validation.
